# Prometheus Configuration for Station2290
# Comprehensive monitoring setup for microservices architecture

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'station2290-production'
    environment: 'production'

# Rules for alerting
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker containers monitoring via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 15s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # API Service monitoring
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # Bot Service monitoring
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:3001']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # Web Application monitoring
  - job_name: 'web'
    static_configs:
      - targets: ['web:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # Admin Panel monitoring
  - job_name: 'adminka'
    static_configs:
      - targets: ['adminka:80']
    scrape_interval: 60s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # Order Panel monitoring
  - job_name: 'order-panel'
    static_configs:
      - targets: ['order-panel:80']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    scrape_timeout: 10s

  # External health checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://station2290.ru
        - https://api.station2290.ru/health
        - https://adminka.station2290.ru
        - https://orders.station2290.ru
        - https://bot.station2290.ru/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://station2290.ru:443
        - https://api.station2290.ru:443
        - https://adminka.station2290.ru:443
        - https://orders.station2290.ru:443
        - https://bot.station2290.ru:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 30s
    metrics_path: /custom-metrics
    params:
      format: ['prometheus']

# Storage configuration (moved to command line args)
# These settings are now configured in the docker-compose command section

# Remote write configuration (optional for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     headers:
#       Authorization: "Bearer YOUR_TOKEN"

# Service discovery configurations
# For dynamic service discovery in Kubernetes or other orchestrators
# kubernetes_sd_configs:
#   - role: pod
#     namespaces:
#       names:
#         - station2290

# File-based service discovery
# - job_name: 'file-sd'
#   file_sd_configs:
#     - files:
#         - '/etc/prometheus/targets/*.json'
#       refresh_interval: 30s

# Consul service discovery (if using Consul)
# consul_sd_configs:
#   - server: 'consul:8500'
#     services: ['station2290-api', 'station2290-bot']